//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_incidents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte
    {
        public string Matricule { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string TP { get; set; }
        public string MP { get; set; }
        public string fonction { get; set; }
        public string servicee { get; set; }
        public string grade { get; set; }
        public string Profilee { get; set; }
    
        public virtual Grade Grade1 { get; set; }
        public virtual Servicee Servicee1 { get; set; }
    }
}
