//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_incidents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fichier
    {
        public Fichier()
        {
            this.InfoFEs = new HashSet<InfoFE>();
        }
    
        public int idfichier { get; set; }
        public Nullable<int> Nincident { get; set; }
        public string famille { get; set; }
        public string equipement { get; set; }
        public string marque { get; set; }
        public string modele { get; set; }
        public string NP { get; set; }
        public string NS { get; set; }
        public string Servicee { get; set; }
        public string Utilisateur { get; set; }
        public string NT { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<System.DateTime> DA { get; set; }
        public Nullable<System.DateTime> DCT { get; set; }
        public Nullable<int> DTT { get; set; }
        public string remarque { get; set; }
    
        public virtual Equipement Equipement1 { get; set; }
        public virtual Famille Famille1 { get; set; }
        public virtual Marque Marque1 { get; set; }
        public virtual Modele Modele1 { get; set; }
        public virtual Incident Incident { get; set; }
        public virtual Servicee Servicee1 { get; set; }
        public virtual ICollection<InfoFE> InfoFEs { get; set; }
    }
}
