//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_incidents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public Incident()
        {
            this.Fichiers = new HashSet<Fichier>();
        }
    
        public int Nincident { get; set; }
        public Nullable<System.DateTime> dateR { get; set; }
        public string typee { get; set; }
        public string servicee { get; set; }
        public string NC { get; set; }
        public string descriptionn { get; set; }
    
        public virtual ICollection<Fichier> Fichiers { get; set; }
        public virtual Servicee Servicee1 { get; set; }
    }
}
