//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_incidents
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFE
    {
        public Nullable<int> idfichier { get; set; }
        public int idfe { get; set; }
        public string FE { get; set; }
        public Nullable<System.DateTime> DD { get; set; }
        public string TF { get; set; }
        public Nullable<System.DateTime> DR { get; set; }
        public string NR { get; set; }
        public Nullable<int> DRF { get; set; }
        public string remarque { get; set; }
    
        public virtual Fichier Fichier { get; set; }
    }
}
