//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_incidents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_des_incidentsEntities : DbContext
    {
        public Gestion_des_incidentsEntities()
            : base("name=Gestion_des_incidentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compte> Comptes { get; set; }
        public DbSet<Equipement> Equipements { get; set; }
        public DbSet<Famille> Familles { get; set; }
        public DbSet<Fichier> Fichiers { get; set; }
        public DbSet<Grade> Grades { get; set; }
        public DbSet<Incident> Incidents { get; set; }
        public DbSet<InfoFE> InfoFEs { get; set; }
        public DbSet<Marque> Marques { get; set; }
        public DbSet<Modele> Modeles { get; set; }
        public DbSet<Servicee> Servicees { get; set; }
    }
}
