//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_des_incidents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicee
    {
        public Servicee()
        {
            this.Comptes = new HashSet<Compte>();
            this.Fichiers = new HashSet<Fichier>();
            this.Incidents = new HashSet<Incident>();
        }
    
        public string idservicee { get; set; }
        public string servicee1 { get; set; }
    
        public virtual ICollection<Compte> Comptes { get; set; }
        public virtual ICollection<Fichier> Fichiers { get; set; }
        public virtual ICollection<Incident> Incidents { get; set; }
    }
}
